### ISSUE TITLE
Indexing a OneToOne User field only takes its username attribute

### ISSUE THREAD

**Issue by neeti25** [algolia/algoliasearch-django#213] opened 2017-07-13 09:39 UTC
I have made two models Student and Teacher by extending Django's User Model in OneToOne fields student and teacher respectively. When i register my Student and Teacher models to algolia, it only takes the username attribute of User in student(or teacher). I am not able to access other fields of User model like first_name, last_name etc. in algolia. How can i access these fields?

**Comment by PLNech** [comment] 2017-07-13 13:48
Hi @neeti25, thank you for reporting this! I wonder if it's not the same issue we have with `ManyToMany` fields in #202. 

Let me investigate this, I'll keep you updated here of my progress!

**Comment by neeti25** [comment] 2017-07-14 05:48
Sure.

**Comment by PLNech** [comment] 2017-08-22 08:57
@neeti25: We just documented a way to index `ManyToMany` fields in 0f70028ad664620c5341fb83c097596c41d6771a, can you check the documented approach and let me know if it works for your usecase? 🙂

**Comment by PLNech** [comment] 2018-01-09 16:04
Closing as 0f70028 introduces a solution and @neeti25 didn't answer the previous comment, suggesting the issue is resolved.

**Closed by PLNech** 2018-01-09 16:04 UTC
Labels: bug
