### ISSUE TITLE
How do I index the data that was in the database, before I integrated it with algoliasearch.

### ISSUE THREAD

**Issue by SaadBinShahid** [algolia/algoliasearch-django#122] opened 2017-01-20 15:20 UTC
How do I index the data that was in the database, before I integrated it with algoliasearch. 

> `python manage.py algolia_reindex`: reindex all the registered models.

It only index when object is created or updated. How to index the data that was entered before algoliasearch integration ?

```
$ python manage.py algolia_reindex
/home/ubuntu/shopsy-pk/API/Provider/models.py:17: RemovedInDjango19Warning: Model class Provider.models.Provider doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Provider(models.Model):
/home/ubuntu/shopsy-pk/API/Provider/models.py:40: RemovedInDjango19Warning: Model class Provider.models.CategoryMappingTemplate doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CategoryMappingTemplate(models.Model):
/home/ubuntu/shopsy-pk/API/Product/models.py:11: RemovedInDjango19Warning: Model class Product.models.Product doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Product(models.Model):
/home/ubuntu/shopsy-pk/API/Product/models.py:85: RemovedInDjango19Warning: Model class Product.models.ProductImage doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ProductImage(models.Model):
The following models were reindexed:
	* Product --> 0
```

**Comment by PLNech** [comment] 2017-06-27 14:18
Hi @SaadBinShahid, thank you for your report and my apologies for the slow reply!

I tried to reproduce your situation, but calling `algolia_reindex` indexed objects created before:

## Steps to reproduce
- Create a django project
- Create a model class `Foo`:
```python
class Foo(models.Model):
    name = models.CharField(max_length=40)
```
- Add algoliasearch-django and the appropriate settings (see [detailed instructions](https://github.com/algolia/algoliasearch-django#install))
- In your `AppConfig`, register the model:
```python
algoliasearch.register(self.get_model('Foo'))
```
- Create a `Foo` object:
```python
Fake.objects.create(name="asd")
```
- Call `algoliasearch_register`:
```sh
./manage.py algolia_reindex
The following models were reindexed:
        * Foo --> 1
```

As you can see in the command's output, the data that was in the database was indexed successfully.

Can you follow these steps and let me know if you still see this bug? I'll close the issue for now as `cannot reproduce`, but feel free to reopen it with steps to reproduce if the bug persists.

**Closed by PLNech** 2017-06-27 14:18 UTC
